name: Output information

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GH context
        run: | 
          echo "GITHUB CONTEXT: ${{ toJSON(github) }}"
